<?php

namespace GenAI\I18n\Processor;

use GenAI\Attribute\AttributeProcessor;
use GenAI\Attribute\Context;
use GenAI\I18n\Attribute\Messages;

/**
 * Compiles per-locale message catalogs into a reflection-free Cache\Messages.
 *
 * Reads every config/messages/<locale>.ini (flat, dotted keys) and bakes
 *   array(locale => array(key => message))
 * into a static Cache\Messages::all(), the way PropertyProcessor bakes app.ini.
 * Always emits the class (empty if there are no catalogs) so the Translator bean
 * can rely on it.
 *
 * Build-time only (PHP 8); the file it writes is PHP 5.3-safe.
 */
class MessagesProcessor implements AttributeProcessor
{
    public function getAttributeClass(): string
    {
        return Messages::class;   // marker — this processor is file-driven (see compile)
    }

    public function process(object $attribute, \Reflector $target): void
    {
        // no-op: catalogs come from config/messages/*.ini, not from attributes
    }

    public function compile(Context $context): void
    {
        $dir = rtrim($context->configDir, "/\\") . '/messages';
        $all = [];
        foreach (glob($dir . '/*.ini') ?: [] as $file) {
            $locale = basename($file, '.ini');
            $parsed = parse_ini_file($file, false, INI_SCANNER_RAW);
            $all[$locale] = is_array($parsed) ? $parsed : [];
        }

        $source = "<?php\n\n"
            . "namespace Cache;\n\n"
            . "// Generated by GenAI\\I18n\\Processor\\MessagesProcessor - do not edit by hand.\n"
            . "// Baked translation catalogs: locale => array(key => message).\n\n"
            . "class Messages\n"
            . "{\n"
            . "    public static function all()\n"
            . "    {\n"
            . "        return " . var_export($all, true) . ";\n"
            . "    }\n"
            . "}\n";

        file_put_contents($context->output('Messages.php'), $source);
    }
}
